name: cultivator_web
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.8.0-278.4.beta

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^15.1.2
  flutter_animate: ^4.5.2
  url_launcher: ^6.3.1
  url_launcher_web: ^2.4.1
  web: ^1.1.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true